//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rubinator3000.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rubinator3000.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;OllSolving&gt;
        ///  &lt;ollPattern number=&quot;0&quot; face=&quot;511&quot; side0=&quot;0&quot; side1=&quot;0&quot; side2=&quot;0&quot; side3=&quot;0&quot; algorithm=&quot;LWDLiDiMiDLDiLi&quot; /&gt;
        ///  &lt;ollPattern number=&quot;1&quot; face=&quot;501&quot; side0=&quot;2&quot; side1=&quot;2&quot; side2=&quot;0&quot; side3=&quot;0&quot; algorithm=&quot;LDLiDiMDLDiLWi&quot; /&gt;
        ///  &lt;ollPattern number=&quot;2&quot; face=&quot;381&quot; side0=&quot;2&quot; side1=&quot;0&quot; side2=&quot;2&quot; side3=&quot;0&quot; algorithm=&quot;LWiLDLDLiDiLWLWLiLiDLDiLWi&quot; /&gt;
        ///  &lt;ollPattern number=&quot;3&quot; face=&quot;341&quot; side0=&quot;2&quot; side1=&quot;2&quot; side2=&quot;2&quot; side3=&quot;2&quot; algorithm=&quot;LiLiULiDDLUiLiDDLi&quot; /&gt;
        ///  &lt;ollPattern [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ollSolving {
            get {
                return ResourceManager.GetString("ollSolving", resourceCulture);
            }
        }
    }
}
