//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RubinatorCore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RubinatorCore.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;OllSolving&gt;  
        ///  &lt;ollPattern number=&quot;1&quot; face=&quot;501&quot; side0=&quot;2&quot; side1=&quot;2&quot; side2=&quot;0&quot; side3=&quot;0&quot; algorithm=&quot;LWDLiDiMiDLDiLi&quot; /&gt;
        ///  &lt;ollPattern number=&quot;2&quot; face=&quot;381&quot; side0=&quot;0&quot; side1=&quot;2&quot; side2=&quot;0&quot; side3=&quot;2&quot; algorithm=&quot;LDLiDiMDLDiLWi&quot; /&gt;
        ///  &lt;ollPattern number=&quot;3&quot; face=&quot;341&quot; side0=&quot;2&quot; side1=&quot;2&quot; side2=&quot;2&quot; side3=&quot;2&quot; algorithm=&quot;LWiLDLDLiDiLWLWLiLiDLDiLWi&quot; /&gt;
        ///  &lt;ollPattern number=&quot;4&quot; face=&quot;506&quot; side0=&quot;0&quot; side1=&quot;5&quot; side2=&quot;0&quot; side3=&quot;0&quot; algorithm=&quot;LiLiULiDDLUiLiDDLi&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ollSolving {
            get {
                return ResourceManager.GetString("ollSolving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;no&quot; ?&gt;
        ///&lt;pllSolving&gt;
        ///    &lt;pllPattern number=&quot;00&quot; face0=&quot;10&quot; face1=&quot;60&quot; face2=&quot;49&quot; face3=&quot;45&quot; algorithm=&quot;RiFRiB2RFiRiB2R2&quot; /&gt;
        ///    &lt;pllPattern number=&quot;01&quot; face0=&quot;15&quot; face1=&quot;40&quot; face2=&quot;30&quot; face3=&quot;19&quot; algorithm=&quot;R2B2RFRiB2RFiR&quot; /&gt;
        ///    &lt;pllPattern number=&quot;02&quot; face0=&quot;59&quot; face1=&quot;25&quot; face2=&quot;59&quot; face3=&quot;25&quot; algorithm=&quot;xiRUiRiDRURiDiRURiDRUiRiDi&quot; /&gt;
        ///    &lt;pllPattern number=&quot;03&quot; face0=&quot;49&quot; face1=&quot;49&quot; face2=&quot;00&quot; face3=&quot;34&quot; algorithm=&quot;RUiRURURUiRiUiR2&quot; /&gt;
        ///    &lt;pllPatte [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pllSolving {
            get {
                return ResourceManager.GetString("pllSolving", resourceCulture);
            }
        }
    }
}
